version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true  

  [[blocks.segments]]
    template = 'ğŸŒ¸{{ .UserName }}'
    foreground = '#000000'
    powerline_symbol = 'î‚´'
    leading_diamond = 'î‚¶'
    background = '#6333AE'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = '#000000'
    powerline_symbol = 'î‚´'
    background = '#AA7EEE'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      home_icon = '~'
      style = 'agnoster_full'

  [[blocks.segments]]
    template = ' {{ .HEAD }}'
    foreground = '#000000'
    powerline_symbol = 'î‚´'
    background = '#BB9DED'
    type = 'git'
    style = 'powerline'

    [blocks.segments.properties]
      branch_icon = 'îœ¥ '
      cherry_pick_icon = 'îŠ› '
      commit_icon = 'ï— '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = 'îœ§ '
      no_commits_icon = 'ïƒƒ '
      rebase_icon = 'îœ¨ '
      revert_icon = 'ïƒ¢ '
      tag_icon = 'ï’ '

[[blocks.segments]]
    template = ' ğŸ—²'
    foreground_templates = [
      "{{if gt .Code 0}}#f38ba8{{end}}",
      "{{if eq .Code 0}}#BB9AF0{{end}}",
    ]
    type = 'text'
    style = 'plain'

[transient_prompt]
foreground_templates = [
      "{{if gt .Code 0}}#f38ba8{{end}}",
      "{{if eq .Code 0}}#BB9AF0{{end}}",
]

template = 'ğŸ—² '

[[blocks]]
  type = "rprompt"
  alignment = 'right'

[[blocks.segments]]
type = "executiontime"
template = "{{ .FormattedMs }} "

[blocks.segments.properties]
threshold = 0
style = "austin"
always_enabled = true

